FROM ruby:2.5.0

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev apt-transport-https
RUN apt-get update && apt-get install -y -o Dpkg::Options::="--force-confold" netcat

RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -yq nodejs

# for yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update -qq && apt-get install -y yarn

# Set an environment variable where the Rails app is installed to inside of Docker image

ENV RAILS_ROOT /var/www/community
RUN mkdir -p $RAILS_ROOT

# Set working directory
WORKDIR $RAILS_ROOT

# Setting env up
ENV RAILS_ENV='production'
ENV RACK_ENV='production'

# Adding gems
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

RUN bundle install --jobs 20 --retry 5 --without development test

# Adding project files, run "rake assets:precompile RAILS_ENV=production" before image building
COPY . .

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-p", "3000"]
