apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: community
spec:
  ports:
    - port: 3000
  selector:
    app: community
    tier: rails
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: app
spec:
  replicas: 2
  selector:
    app: community
    tier: rails
  template:
    metadata:
      name: rails
      labels:
        app: community
        tier: rails
    spec:
      containers:
      - name: rails
        image: psmir/community_app:latest
        args: ["rails s -p 3000 -b 0.0.0.0"]
        env:
        - name: DATABASE_URL
          value: "postgres"
        - name: DATABASE_NAME
          value: "community_production"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: "db-user"
              key: "username"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "db-user-pass"
              key: "password"         
        - name: ACTION_CABLE_URL
          value: "ws://community.com/cable"
        - name: ATION_CABLE_ALLOWED_REQUEST_ORIGINS
          value: "http://community.com|http://localhost"
        ports:
        - containerPort: 3000
