apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: community
spec:
  ports:
    - port: 3000
  selector:
    app: community
    tier: rails
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: app
spec:
  replicas: 1
  selector:
    app: community
    tier: rails
  template:
    metadata:
      name: rails
      labels:
        app: community
        tier: rails
    spec:
      containers:
      - name: rails
        image: psmir/community_app:latest
        env:
        - name: DATABASE_USER
          value: "community_user"
        - name: DATABASE_PASSWORD
          value: "mysecretpass"
        - name: ACTION_CABLE_URL
          value: "ws://community.com/cable"
        - name: ACTION_CABLE_ALLOWED_REQUEST_ORIGINS
          value: "http://community.com|http://localhost"
        - name: RAILS_ENV
          value: "production"
        ports:
        - containerPort: 3000
