apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: community
spec:
  ports:
    - port: 5432
  selector:
    app: community
    tier: db
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: "community-disk"
    fsType: "ext4"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: db
  labels:
    app: community
spec:
  replicas: 1
  selector:
    app: community
    tier: db
  template:
    metadata:
      name: db
      labels:
        app: community
        tier: db
    spec:
      volumes:
      - name: db-pv
        persistentVolumeClaim:
          claimName: db-pvc
      containers:
      - image: postgres:9.5.3
        name: db
        env:
        - name: POSTGRES_USER
          value: "community_user"
        - name: POSTGRES_PASSWORD
          value: "mysecretpass"
        - name: POSTGRES_DB
          value: community_production
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
          name: db
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: db-pv