apiVersion: batch/v1
kind: Job
metadata:
  name: setup
spec:
  template:
    metadata:
      name: setup
    spec:
      containers:
      - name: setup
        image: psmir/community_app:latest
        command: ["/bin/sh"]
        args: ["-c", "rake db:migrate"]
        env:
        - name: DATABASE_USER
          value: "community_user"
        - name: DATABASE_PASSWORD
          value: "mysecretpass"   
        - name: RAILS_ENV
          value: "production"    
        - name: RACK_ENV
          value: "production"    
      restartPolicy: Never
