apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: community
spec:
  type: LoadBalancer
  port: 80
  - targetPort: 80
  selector:
    app: community
    tier: web
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: web
spec:
  replicas: 1
  selector:
    app: community
    tier: web
  template:
    metadata:
      name: web
      labels:
        app: community
        tier: web
    spec:
      containers:
      - name: web
        image: psmir/community_web:latest
        ports:
        - containerPort: 80
