development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
#  adapter: redis
#  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
#  channel_prefix: hyper_community_production
