default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['COMMUNITY_DATABASE_USER'] %>
  password: <%= ENV['COMMUNITY_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: community_development
  host: localhost

test:
  <<: *default
  database: community_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  pool: 5
  host: db
  database: community_production

