default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: community_development
  host: localhost

test:
  <<: *default
  database: community_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV['DATABASE_NAME'] %>

