default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: 5432
development:
  <<: *default
  database: community_development
  host: localhost

test:
  <<: *default
  database: community_test
  host: localhost

production:
  <<: *default  
  host: db
  database: community_production

  
